create table if not exists portfolio_content (
  section_key text primary key,
  content jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table portfolio_content enable row level security;

drop policy if exists "Public can read portfolio content" on portfolio_content;
create policy "Public can read portfolio content"
on portfolio_content
for select
using (true);

insert into portfolio_content (section_key, content)
values
  ('experiences', '[]'::jsonb),
  ('projects', '[]'::jsonb),
  ('news', '[]'::jsonb),
  ('achievements', '[]'::jsonb),
  ('site_profile', '{"image":{"src":"","alt":"Naila Azahra profile photo"}}'::jsonb)
on conflict (section_key) do nothing;

create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 100),
  email text not null check (char_length(trim(email)) between 5 and 254),
  message text not null check (char_length(trim(message)) between 5 and 4000),
  created_at timestamptz not null default now()
);

alter table contact_messages enable row level security;

drop policy if exists "Public can submit contact messages" on contact_messages;
create policy "Public can submit contact messages"
on contact_messages
for insert
with check (true);

-- Portfolio assets for builder cover, documentation, and certificate uploads.
insert into storage.buckets (id, name, public)
values ('portfolio-assets', 'portfolio-assets', true)
on conflict (id) do update set public = true;

drop policy if exists "Public read portfolio assets" on storage.objects;
create policy "Public read portfolio assets"
on storage.objects
for select
using (bucket_id = 'portfolio-assets');

drop policy if exists "Upload portfolio assets" on storage.objects;
create policy "Upload portfolio assets"
on storage.objects
for insert
with check (bucket_id = 'portfolio-assets');

-- Separate public bucket for the navbar profile photograph.
insert into storage.buckets (id, name, public)
values ('profile-assets', 'profile-assets', true)
on conflict (id) do update set public = true;

drop policy if exists "Public read profile assets" on storage.objects;
create policy "Public read profile assets"
on storage.objects
for select
using (bucket_id = 'profile-assets');

drop policy if exists "Upload profile assets" on storage.objects;
create policy "Upload profile assets"
on storage.objects
for insert
with check (bucket_id = 'profile-assets');
